# theme.toml template for a Hugo theme

name = "Mustard Seed Capital"
license = ""
licenselink = ""
description = ""
homepage = "https://mustardseed.capital/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Mustard Seed Capital"
  homepage = "https://mustardseed.capital/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""